### PR TITLE
Accordion now works on the front end

### PR DESCRIPTION
**Pull request by mak001**
- ~~uses bootstrap's collapse~~
  - uses jquery ui's accordion

### CODE REVIEW

**Comment by korthjp17** [comment]
I'm wondering if we want to use jquery UI instead of bootstrap as the default accordion. That makes it a bit more universal in case we aren't using BS for the theme. When/if we use something other than BS, it might add some extra load time on the site since it's a bit bulky.

@jsirish any thoughts?

**Comment by korthjp17** [comment]
pulled it down and it seems to be working 👍

**Comment by jsirish** [comment]
Ping #33

**Comment by jsirish** [comment]
Just realized this won’t effect #33 so nvm

**Review by jsirish — APPROVED** [review]

**Pull request merged**
